export const appName = 'TwineMedia'
export const filesRoot = 'http://localhost:8090/download/'
export const thumbsRoot = 'http://localhost:8090/thumbnail/'
export const apiRoot = 'http://localhost:8090/api/v1/'
export const eventBusUrl = 'http://localhost:8090/eventbus'
export const listTypes = ['Standard', 'Automatically Populated']
export const listVisibilities = ['Private', 'Public']
export const version = '1.5.0'
export const apiVersions = ['v1']